[package]
name = "nuzlocke-tracker"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.10.2"
actix-files = "0.6.6"
rinja = "0.3.5"
rinja_actix = "0.3.5"
serde = {version = "1.0.219", features = ["derive"]}
serde_yaml_ng = "0.10.0"
tokio = {version = "1.44.1", features = ["full"]}
